globalThis.CODEX_SPELL_DATA = [
  {
    "key": "truques-1",
    "title": "🎵 Nota Cortante",
    "level": 0,
    "kind": "completa",
    "source": "✨ Arcana / 🎭 Expressiva",
    "manifestation": "💥 Ruptura",
    "cast": "1 Ação",
    "range": "18 m",
    "duration": "Instantânea",
    "components": "V, S",
    "area": "🎯 Alvo Único — criatura a até 18 m",
    "conjuration": "V: uma nota, assobio, estalo ou emissão sonora intencional. S: gesto de projeção ou marcação do alvo. Material: Nenhum.",
    "effect": "Ataque Mágico à distância; 1d8 Trovão.",
    "limitation": "Não atravessa automaticamente barreiras sólidas.",
    "damage": "1d8 Trov",
    "attack": true,
    "save": ""
  },
  {
    "key": "truques-2",
    "title": "⚡ Faísca",
    "level": 0,
    "kind": "completa",
    "source": "✨ Arcana",
    "manifestation": "💥 Ruptura",
    "cast": "1 Ação",
    "range": "9 m",
    "duration": "Instantânea",
    "components": "S",
    "area": "🎯 Alvo Único — criatura/objeto a até 9 m",
    "conjuration": "S: gesto rápido de descarga com mão, ferramenta ou foco. Material: Nenhum.",
    "effect": "Ataque Mágico; 1d6 Elétrico. Também pode gerar pequena faísca utilitária.",
    "limitation": "Não sustenta corrente elétrica.",
    "damage": "1d6 El",
    "attack": true,
    "save": ""
  },
  {
    "key": "truques-3",
    "title": "❄️ Toque de Geada",
    "level": 0,
    "kind": "completa",
    "source": "✨ Arcana / 🌿 Natural",
    "manifestation": "💥 Ruptura",
    "cast": "1 Ação",
    "range": "9 m",
    "duration": "1 rodada",
    "components": "V, S",
    "area": "🎯 Alvo Único — criatura a até 9 m",
    "conjuration": "V: sopro curto ou palavra fria. S: gesto de condensação. Material: Nenhum.",
    "effect": "Ataque Mágico; 1d6 Frio e -1,5 m de Deslocamento.",
    "limitation": "A redução não acumula.",
    "damage": "1d6 Frio",
    "attack": true,
    "save": ""
  },
  {
    "key": "truques-4",
    "title": "🫨 Vibração Incômoda",
    "level": 0,
    "kind": "completa",
    "source": "🎭 Expressiva / ✨ Arcana",
    "manifestation": "🎭 Influência",
    "cast": "1 Ação",
    "range": "12 m",
    "duration": "Até seu próximo turno",
    "components": "V, S",
    "area": "🎯 Alvo Único — criatura a até 12 m",
    "conjuration": "V: ritmo, batida ou frequência repetida. S: gesto cadenciado. Material: Nenhum.",
    "effect": "CON; falha: -1d4 no próximo teste de habilidade de FOR ou DES.",
    "limitation": "Não afeta ataques ou Salvaguardas.",
    "damage": "1d4 no",
    "attack": true,
    "save": "CON"
  },
  {
    "key": "truques-5",
    "title": "🌬️ Sopro Repentino",
    "level": 0,
    "kind": "completa",
    "source": "🌿 Natural / ✨ Arcana",
    "manifestation": "🌀 Alteração",
    "cast": "1 Ação",
    "range": "Cone 3 m",
    "duration": "Instantânea",
    "components": "V, S",
    "area": "🔺 Cone de 3 m a partir do conjurador",
    "conjuration": "V: sopro audível. S: gesto amplo de expulsão. Material: Nenhum.",
    "effect": "FOR; falha: empurra 1,5 m criaturas elegíveis. Move poeira e objetos muito leves.",
    "limitation": "Não cria vento sustentado.",
    "damage": "",
    "attack": false,
    "save": "FOR"
  },
  {
    "key": "truques-6",
    "title": "🌱 Laço de Raiz",
    "level": 0,
    "kind": "completa",
    "source": "🌿 Natural",
    "manifestation": "🌀 Alteração",
    "cast": "1 Ação",
    "range": "9 m",
    "duration": "1 rodada",
    "components": "V, S, M",
    "area": "🌊 Superfície / 🎯 Alvo — vegetação junto a criatura a até 9 m",
    "conjuration": "V: chamada curta ao crescimento. S: gesto de enroscar. M: vegetação real próxima ao alvo. Material: Obrigatório, não consumido.",
    "effect": "DES; falha: perde 3 m de Deslocamento.",
    "limitation": "Não funciona sem vegetação apropriada.",
    "damage": "",
    "attack": false,
    "save": "DES"
  },
  {
    "key": "truques-7",
    "title": "✨ Luz de Vagalume",
    "level": 0,
    "kind": "completa",
    "source": "✨ Arcana / 🌿 Natural",
    "manifestation": "🕸️ Manifestação",
    "cast": "1 Ação",
    "range": "Toque ou 3 m",
    "duration": "1 hora",
    "components": "V, S, M/F",
    "area": "🤝 Toque / 🎯 Objeto ou ponto próximo",
    "conjuration": "V: palavra ou som breve. S: gesto de acender. M: pólen luminoso, asa translúcida ou pequeno cristal fosco. Material: Comum, não consumido; pode ser substituído por Foco.",
    "effect": "3 m Luz Plena + 3 m Penumbra.",
    "limitation": "A luz denuncia posição.",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "truques-8",
    "title": "🪶 Mão de Brisa",
    "level": 0,
    "kind": "completa",
    "source": "✨ Arcana",
    "manifestation": "🕸️ Manifestação",
    "cast": "1 Ação",
    "range": "9 m",
    "duration": "Até 1 min",
    "components": "S",
    "area": "🎯 Alvo Único — objeto minúsculo a até 9 m",
    "conjuration": "S: gesto contínuo imitando manipulação manual. Material: Nenhum.",
    "effect": "Manipula objetos minúsculos e fechos simples.",
    "limitation": "Não ataca nem ergue peso relevante.",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "truques-9",
    "title": "🌿 Sussurro das Folhas",
    "level": 0,
    "kind": "completa",
    "source": "🌿 Natural / 🎭 Expressiva",
    "manifestation": "🎭 Influência",
    "cast": "1 Ação",
    "range": "18 m",
    "duration": "Até 1 min",
    "components": "V, S",
    "area": "📍 Ponto — efeito sensorial em ponto a até 18 m",
    "conjuration": "V: sussurro curto. S: gesto apontando o ponto do som. Material: Nenhum.",
    "effect": "Cria pequenos sons e movimentos naturais.",
    "limitation": "Não cria fala ou criatura ilusória.",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "truques-10",
    "title": "🔥 Centelha de Brasa",
    "level": 0,
    "kind": "completa",
    "source": "✨ Arcana / 🌿 Natural",
    "manifestation": "🌀 Alteração",
    "cast": "1 Ação",
    "range": "Toque",
    "duration": "Breve",
    "components": "V, S, M/F",
    "area": "🤝 Toque — objeto/material inflamável",
    "conjuration": "V: sopro ou palavra de ignição. S: fricção/estalo. M: fibra seca, carvão miúdo ou casca queimada. Material: Comum, não consumido; pode ser substituído por Foco.",
    "effect": "Gera pequena brasa/calor para utilidade.",
    "limitation": "Não é ataque.",
    "damage": "",
    "attack": true,
    "save": ""
  },
  {
    "key": "truques-11",
    "title": "🎭 Pequeno Engano",
    "level": 0,
    "kind": "completa",
    "source": "✨ Arcana / 🎭 Expressiva",
    "manifestation": "🎭 Influência",
    "cast": "1 Ação",
    "range": "9 m",
    "duration": "Até 1 min",
    "components": "V, S",
    "area": "📍 Ponto — pequena ilusão a até 9 m",
    "conjuration": "V: som ou frase curta se a ilusão for sonora. S: desenho/gesto se for visual. Material: Nenhum.",
    "effect": "Cria um som simples OU imagem estática pequena.",
    "limitation": "Não cria criatura complexa.",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "truques-12",
    "title": "🗣️ Voz Carregada",
    "level": 0,
    "kind": "completa",
    "source": "🎭 Expressiva / ✨ Arcana",
    "manifestation": "🎭 Influência",
    "cast": "1 Ação",
    "range": "36 m",
    "duration": "Até 1 min",
    "components": "V",
    "area": "📍 Ponto/Direção — projeção vocal a até 36 m",
    "conjuration": "V: a própria mensagem pronunciada. Material: Nenhum.",
    "effect": "Sua voz chega clara a um ponto distante.",
    "limitation": "Não é secreta nem telepática.",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "truques-13",
    "title": "💫 Compasso Encorajador",
    "level": 0,
    "kind": "completa",
    "source": "🎭 Expressiva / 👻 Espiritual",
    "manifestation": "🛡️ Proteção",
    "cast": "1 Ação",
    "range": "9 m",
    "duration": "1 rodada",
    "components": "V ou S",
    "area": "🎯 Alvo Único — aliado a até 9 m",
    "conjuration": "V: frase/ritmo encorajador OU S: gesto expressivo reconhecível. Material: Nenhum.",
    "effect": "Aliado recebe +1 no próximo teste de habilidade.",
    "limitation": "Não afeta ataque ou Salvaguarda.",
    "damage": "",
    "attack": true,
    "save": ""
  },
  {
    "key": "truques-14",
    "title": "🛡️ Reflexo Instintivo",
    "level": 0,
    "kind": "completa",
    "source": "✨ Arcana",
    "manifestation": "🛡️ Proteção",
    "cast": "Reação",
    "range": "Pessoal",
    "duration": "Instantânea",
    "components": "S",
    "area": "🧍 Pessoal — reação defensiva",
    "conjuration": "S: gesto defensivo rápido. Material: Nenhum.",
    "effect": "Reduz dano de ataque percebido em 1d4.",
    "limitation": "Não afeta dano ambiental.",
    "damage": "1d4",
    "attack": true,
    "save": ""
  },
  {
    "key": "truques-15",
    "title": "🌫️ Vestígio",
    "level": 0,
    "kind": "completa",
    "source": "👻 Espiritual / ✨ Arcana",
    "manifestation": "👁️ Percepção",
    "cast": "1 Ação",
    "range": "Toque",
    "duration": "Instantânea",
    "components": "S, M",
    "area": "🤝 Toque — objeto ou superfície",
    "conjuration": "S: contato concentrado. M: pó, fragmento ou resíduo do próprio objeto/local. Material: Especial, não consumido.",
    "effect": "Detecta presença emocional ou mágica incomum.",
    "limitation": "Não revela quem/quando/por quê.",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "truques-16",
    "title": "👁️ Pressentir",
    "level": 0,
    "kind": "completa",
    "source": "👻 Espiritual",
    "manifestation": "👁️ Percepção",
    "cast": "1 Ação",
    "range": "Visão até 6 m",
    "duration": "Até fim do turno",
    "components": "V, S",
    "area": "🧍 Pessoal — percepção em até 6 m",
    "conjuration": "V: respiração ou palavra de foco. S: gesto sobre olhos/antenas/sentidos. Material: Nenhum.",
    "effect": "Revela silhuetas sutis de pegadas, marcas de mão, arrasto e manipulação física.",
    "limitation": "Mostra vestígio, não significado.",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "truques-17",
    "title": "🕯️ Marca Efêmera",
    "level": 0,
    "kind": "completa",
    "source": "✨ Arcana",
    "manifestation": "🕸️ Manifestação",
    "cast": "1 Ação",
    "range": "Toque",
    "duration": "8 horas",
    "components": "S, M/F",
    "area": "🤝 Toque — objeto ou superfície",
    "conjuration": "S: desenhar o símbolo. M: pigmento, pó mineral ou seiva colorida. Material: Comum, não consumido; pode ser substituído por Foco.",
    "effect": "Cria pequeno símbolo ou palavra curta.",
    "limitation": "Não funciona como rastreador.",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "truques-18",
    "title": "🕸️ Fio Mágico",
    "level": 0,
    "kind": "completa",
    "source": "✨ Arcana",
    "manifestation": "🕸️ Manifestação",
    "cast": "1 Ação",
    "range": "3 m",
    "duration": "Até 10 min",
    "components": "S, M/F",
    "area": "🕸️ Ancorada — entre pontos/objetos a até 3 m",
    "conjuration": "S: gesto de fiar. M: fibra, fio, seda ou filamento curto. Material: Comum, não consumido; pode ser substituído por Foco.",
    "effect": "Cria fio temporário para objetos e montagens leves.",
    "limitation": "Não prende criaturas.",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "truques-19",
    "title": "💧 Orvalho Vivo",
    "level": 0,
    "kind": "completa",
    "source": "🌿 Natural",
    "manifestation": "🌀 Alteração",
    "cast": "1 Ação",
    "range": "3 m",
    "duration": "Até 1 min",
    "components": "S, M",
    "area": "🌊 Superfície — pequena quantidade de água a até 3 m",
    "conjuration": "S: gesto de condução. M: água real já existente. Material: Obrigatório, não consumido.",
    "effect": "Manipula pequena quantidade de água.",
    "limitation": "Não cria água.",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "truques-20",
    "title": "🪞 Reflexo Fugaz",
    "level": 0,
    "kind": "completa",
    "source": "✨ Arcana / 🎭 Expressiva",
    "manifestation": "🎭 Influência",
    "cast": "Ação Bônus",
    "range": "Pessoal",
    "duration": "Até seu próximo turno",
    "components": "S",
    "area": "🧍 Pessoal",
    "conjuration": "S: gesto de deslocamento corporal. Material: Nenhum.",
    "effect": "Próximo ataque contra você sofre -1d4.",
    "limitation": "Não concede Invisibilidade.",
    "damage": "1d4",
    "attack": true,
    "save": ""
  },
  {
    "key": "truques-21",
    "title": "🩹 Último Fôlego",
    "level": 0,
    "kind": "completa",
    "source": "👻 Espiritual / ✨ Arcana",
    "manifestation": "🛡️ Proteção",
    "cast": "1 Ação",
    "range": "Toque",
    "duration": "Instantânea",
    "components": "V, S",
    "area": "🤝 Toque — criatura a 0 PV",
    "conjuration": "V: palavra curta de sustentação. S: contato firme sobre o corpo. Material: Nenhum.",
    "effect": "Estabiliza criatura viva a 0 PV.",
    "limitation": "Não recupera PV.",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "truques-22",
    "title": "🧪 Cuspe Cáustico",
    "level": 0,
    "kind": "completa",
    "source": "🌿 Natural / ✨ Arcana",
    "manifestation": "💥 Ruptura",
    "cast": "1 Ação",
    "range": "9 m",
    "duration": "Instantânea",
    "components": "V, S, M/F",
    "area": "🎯 Alvo Único — criatura a até 9 m",
    "conjuration": "V: expulsão curta. S: gesto de projeção. M: gota de seiva ácida ou pó corrosivo. Material: Comum, não consumido; Foco substitui.",
    "effect": "DES; falha: 1d6 Ácido.",
    "limitation": "Não substitui ferramenta de corrosão pesada.",
    "damage": "1d6",
    "attack": false,
    "save": "DES"
  },
  {
    "key": "truques-23",
    "title": "☠️ Névoa Tóxica",
    "level": 0,
    "kind": "completa",
    "source": "🌿 Natural",
    "manifestation": "💥 Ruptura",
    "cast": "1 Ação",
    "range": "Cone 3 m",
    "duration": "Instantânea",
    "components": "V, S, M",
    "area": "🔺 Cone de 3 m a partir do conjurador",
    "conjuration": "V: sopro. S: gesto de dispersão. M: esporo, toxina vegetal ou resíduo venenoso. Material: Consumível; é gasto ao conjurar.",
    "effect": "CON; falha: 1d8 Veneno.",
    "limitation": "Imunidade a Veneno ignora.",
    "damage": "1d8 Veneno",
    "attack": false,
    "save": "CON"
  },
  {
    "key": "truques-24",
    "title": "🔥 Brasa Arremessada",
    "level": 0,
    "kind": "completa",
    "source": "✨ Arcana",
    "manifestation": "💥 Ruptura",
    "cast": "1 Ação",
    "range": "18 m",
    "duration": "Instantânea",
    "components": "V, S, M/F",
    "area": "🎯 Alvo Único — criatura/objeto a até 18 m",
    "conjuration": "V: palavra de ignição. S: arremesso. M: carvão, resina seca ou centelha presa. Material: Comum, não consumido; Foco substitui.",
    "effect": "Ataque Mágico; 1d8 Fogo.",
    "limitation": "Só incendeia material realmente inflamável.",
    "damage": "1d8 Fogo",
    "attack": true,
    "save": ""
  },
  {
    "key": "truques-25",
    "title": "🪡 Reparar",
    "level": 0,
    "kind": "completa",
    "source": "✨ Arcana",
    "manifestation": "🌀 Alteração",
    "cast": "1 min",
    "range": "Toque",
    "duration": "Instantânea",
    "components": "S, M",
    "area": "🤝 Toque — objeto danificado",
    "conjuration": "S: reconstrução cuidadosa. M: fragmentos do próprio objeto ou material compatível. Material: Obrigatório quando houver perda de material; não consumido além do que for necessário ao reparo.",
    "effect": "Repara rasgo/rachadura simples.",
    "limitation": "Reparar conserta; Gambiarra cria.",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "truques-26",
    "title": "💬 Sussurro Distante",
    "level": 0,
    "kind": "completa",
    "source": "🎭 Expressiva / ✨ Arcana",
    "manifestation": "🎭 Influência",
    "cast": "1 Ação",
    "range": "18 m",
    "duration": "Instantânea",
    "components": "V, S",
    "area": "🎯 Alvo Único — criatura a até 18 m",
    "conjuration": "V: a mensagem sussurrada. S: apontar ou marcar o alvo. Material: Nenhum.",
    "effect": "Envia frase curta e privada; alvo pode responder uma vez.",
    "limitation": "Não é telepatia plena.",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "truques-27",
    "title": "🪄 Pequena Maravilha",
    "level": 0,
    "kind": "completa",
    "source": "✨ Arcana",
    "manifestation": "🌀 Alteração",
    "cast": "1 Ação",
    "range": "3 m",
    "duration": "Breve",
    "components": "V ou S",
    "area": "📍 Ponto / 🎯 Objeto — até 3 m",
    "conjuration": "V ou S conforme o efeito trivial criado. Material: Nenhum.",
    "effect": "Limpa/suja, muda cheiro leve, aquece/esfria levemente, colore ou cria efeito sensorial trivial.",
    "limitation": "Não substitui outro Truque específico.",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "truques-28",
    "title": "🕯️ Toque Funesto",
    "level": 0,
    "kind": "completa",
    "source": "👻 Espiritual",
    "manifestation": "💥 Ruptura",
    "cast": "1 Ação",
    "range": "9 m",
    "duration": "1 rodada",
    "components": "V, S",
    "area": "🎯 Alvo Único — criatura a até 9 m",
    "conjuration": "V: palavra espectral. S: gesto de toque à distância. Material: Nenhum.",
    "effect": "Ataque Mágico; 1d6 Necrótico e reduz primeira cura recebida em 1.",
    "limitation": "A redução não acumula.",
    "damage": "1d6 Necr",
    "attack": true,
    "save": ""
  },
  {
    "key": "truques-29",
    "title": "🗯️ Palavra Ferina",
    "level": 0,
    "kind": "completa",
    "source": "🎭 Expressiva / 👻 Espiritual",
    "manifestation": "🎭 Influência",
    "cast": "1 Ação",
    "range": "18 m",
    "duration": "1 rodada",
    "components": "V ou S",
    "area": "🎯 Alvo Único — criatura a até 18 m",
    "conjuration": "V: frase, nota ou som hostil; ou S: gesto expressivo perceptível. Material: Nenhum.",
    "effect": "SAB; falha: 1d6 Psíquico e -1d4 no próximo ataque.",
    "limitation": "Alvo precisa perceber a manifestação.",
    "damage": "1d6 Ps",
    "attack": true,
    "save": "SAB"
  },
  {
    "key": "truques-30",
    "title": "🌿 Arma Desperta",
    "level": 0,
    "kind": "completa",
    "source": "🌿 Natural",
    "manifestation": "🌀 Alteração",
    "cast": "Ação Bônus",
    "range": "Toque",
    "duration": "1 min",
    "components": "V, S, M",
    "area": "🤝 Toque — arma de material natural",
    "conjuration": "V: chamado curto. S: toque/gesto sobre a arma. M: arma feita predominantemente de material natural. Material: Obrigatório, não consumido.",
    "effect": "Permite usar Atributo de Conjuração para ataque/dano com a arma, se a Classe permitir.",
    "limitation": "Não concede Ataque Extra.",
    "damage": "",
    "attack": true,
    "save": ""
  },
  {
    "key": "m1-1",
    "title": "🛡️ Casulo Reativo",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S",
    "area": "🧍 Pessoal — reação ao dano elemental",
    "conjuration": "V: palavra curta de proteção. S: gesto defensivo rápido. Material: Nenhum.",
    "effect": "Ao sofrer Ácido, Frio, Fogo, Elétrico ou Trovão, ganha Resistência ao tipo que ativou a magia, inclusive contra o dano gatilho.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-2",
    "title": "🔥 Sopro de Brasa",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "🔺 Cone de 4,5 m",
    "conjuration": "V: exalação ou palavra ígnea. S: gesto em cone. M: carvão, resina seca ou fibra queimada. Material: Comum, não consumido; Foco substitui.",
    "effect": "DES; falha: 3d6 Fogo, sucesso: metade. Materiais extremamente inflamáveis podem pegar fogo.",
    "limitation": "",
    "damage": "3d6 Fogo",
    "attack": false,
    "save": "DES"
  },
  {
    "key": "m1-3",
    "title": "🌿 Abraço do Matagal",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M",
    "area": "🟫 Zona / 🌊 Superfície — área de 6 × 6 m a até 18 m",
    "conjuration": "V: chamada ao matagal. S: gesto de enroscar. M: vegetação real na área. Material: Obrigatório, não consumido.",
    "effect": "Vegetação existente torna a área Terreno Difícil. FOR; falha: Contida. Ação para escapar.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": "FOR"
  },
  {
    "key": "m1-4",
    "title": "💚 Pulso Restaurador",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "🤝 Toque — uma criatura",
    "conjuration": "V: palavra ou melodia restauradora. S: toque. M: gota de seiva limpa, pétala medicinal ou fibra viva. Material: Comum, não consumido; Foco substitui.",
    "effect": "Cura 1d8 + Modificador de Conjuração PV. +1d8 por Melodia acima da 1ª.",
    "limitation": "",
    "damage": "1d8 + Modificador de",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-5",
    "title": "🌫️ Manto de Névoa",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "⭕ Raio de 6 m centrado em ponto a até 18 m",
    "conjuration": "V: sopro prolongado. S: gesto circular. M: gota d'água, orvalho ou folha úmida. Material: Comum, não consumido; Foco substitui.",
    "effect": "Cria névoa densa; área fica Fortemente Obscurecida. Vento forte pode dispersar.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-6",
    "title": "🎭 Rosto Emprestado",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "🧍 Pessoal",
    "conjuration": "V: frase de identidade. S: gesto sobre o rosto/corpo. M: pigmento, pedaço de tecido ou fragmento de espelho. Material: Comum, não consumido; Foco substitui.",
    "effect": "Altera ilusoriamente aparência e vestimenta aparente; não muda anatomia real.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-7",
    "title": "🪶 Queda de Pluma",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, M/F",
    "area": "🎯 Múltiplos Alvos — até 5 criaturas a até 18 m",
    "conjuration": "V: palavra de alívio. M: pena, asa leve, fibra de dente-de-leão ou equivalente. Material: Comum, não consumido; Foco substitui.",
    "effect": "Até 5 criaturas em queda têm a queda desacelerada e evitam dano normal de queda.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-8",
    "title": "👁️ Olhar do Invisível",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "🧍 Pessoal — percepção ao redor",
    "conjuration": "V: palavra de abertura. S: gesto sobre os sentidos. M: cristal fosco, olho seco de inseto ou pó prismático. Material: Comum, não consumido; Foco substitui.",
    "effect": "Percebe magia próxima e sua Fonte predominante; não identifica automaticamente a magia.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-9",
    "title": "🎵 Sussurro Dissonante",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V",
    "area": "🎯 Alvo Único — criatura a até 18 m",
    "conjuration": "V: o próprio sussurro, nota ou frase perturbadora. Material: Nenhum.",
    "effect": "SAB; falha: 3d6 Psíquico e usa Reação para se afastar pelo caminho seguro. Sucesso: metade.",
    "limitation": "",
    "damage": "3d6 Ps",
    "attack": false,
    "save": "SAB"
  },
  {
    "key": "m1-10",
    "title": "🕯️ Sentinela Silenciosa",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M",
    "area": "🕸️ Ancorada — área, entrada ou passagem a até 9 m",
    "conjuration": "V: palavra de vigília. S: traçar o limite. M: fio, pó, sementes, sinos minúsculos ou marcas físicas no perímetro. Material: Obrigatório, não consumido.",
    "effect": "Delimita área/entrada e gera alerta quando criatura não autorizada atravessa.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-11",
    "title": "🐞 Elo com a Fera",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "🎯 Alvo Único — criatura animal a até 9 m",
    "conjuration": "V: vocalização amigável. S: gesto não ameaçador. M: alimento, odor ou pequeno objeto de interesse para a criatura. Material: Comum; normalmente não consumido pelo feitiço, embora a criatura possa consumir o alimento.",
    "effect": "Criatura animal faz SAB; falha: reconhece você como não hostil. Não é dominação.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": "SAB"
  },
  {
    "key": "m1-12",
    "title": "✨ Ritmo Afortunado",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S",
    "area": "🎯 Múltiplos Alvos — até 3 criaturas a até 9 m",
    "conjuration": "V: ritmo/mantra. S: condução do compasso. Material: Nenhum.",
    "effect": "Até 3 criaturas adicionam 1d4 a Ataques e Salvaguardas.",
    "limitation": "",
    "damage": "1d4 a",
    "attack": true,
    "save": ""
  },
  {
    "key": "m1-13",
    "title": "🕷️ Mau Presságio",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "🎯 Múltiplos Alvos — até 3 criaturas a até 9 m",
    "conjuration": "V: frase ominosa. S: gesto de marcação. M: fio escuro, casca rachada ou semente seca. Material: Comum, não consumido; Foco substitui.",
    "effect": "Até 3 criaturas fazem CAR; falha: -1d4 em Ataques e Salvaguardas.",
    "limitation": "",
    "damage": "1d4 em",
    "attack": true,
    "save": "CAR"
  },
  {
    "key": "m1-14",
    "title": "😨 Presença do Predador",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "🎯 Alvo Único — criatura a até 18 m",
    "conjuration": "V: som ameaçador. S: postura de domínio. M: presa, ferrão, fragmento de carapaça ou pena de predador. Material: Comum, não consumido; Foco substitui.",
    "effect": "SAB; falha: Amedrontada; repete no fim de cada turno.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": "SAB"
  },
  {
    "key": "m1-15",
    "title": "💞 Fascínio",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S",
    "area": "🎯 Alvo Único — criatura a até 9 m",
    "conjuration": "V: voz, canto ou fala cativante. S: gesto expressivo. Material: Nenhum.",
    "effect": "SAB; falha: Enfeitiçada. Não é dominação.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": "SAB"
  },
  {
    "key": "m1-16",
    "title": "🗣️ Palavra Imperiosa",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V",
    "area": "🎯 Alvo Único — criatura a até 18 m",
    "conjuration": "V: a ordem pronunciada. Material: Nenhum.",
    "effect": "Ordem curta; SAB; falha: alvo tenta obedecer. Ordem obviamente suicida falha.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": "SAB"
  },
  {
    "key": "m1-17",
    "title": "🦗 Salto do Gafanhoto",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "🤝 Toque — uma criatura",
    "conjuration": "V: palavra curta. S: toque nas pernas/corpo. M: perna seca de inseto, fibra elástica ou mola vegetal. Material: Comum, não consumido; Foco substitui.",
    "effect": "Triplica a distância de salto do alvo.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-18",
    "title": "🐜 Passos Ligeiros",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "🤝 Toque — uma criatura",
    "conjuration": "V: palavra de impulso. S: toque nos pés/pernas. M: semente leve, asa ou fragmento de casca lisa. Material: Comum, não consumido; Foco substitui.",
    "effect": "+3 m de Deslocamento.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-19",
    "title": "🎯 Marca do Caçador",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "🎯 Alvo Único — criatura a até 18 m",
    "conjuration": "V: nome/apelido da presa ou chamado curto. S: gesto de marca. M: fio, sangue seco, pelo, escama ou sinal da presa quando disponível. Material: Comum; Foco pode substituir se a magia não exigir amostra real.",
    "effect": "Marca alvo: seus ataques causam +1d6 e você tem Vantagem para rastreá-lo.",
    "limitation": "",
    "damage": "1d6 e",
    "attack": true,
    "save": ""
  },
  {
    "key": "m1-20",
    "title": "🌈 Poeira de Vagalume",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M",
    "area": "⬛ Cubo de 6 m em ponto a até 18 m",
    "conjuration": "V: chamado de luz. S: gesto de dispersão. M: pólen luminoso, pó de asa ou esporos brilhantes. Material: Consumível.",
    "effect": "DES; falha: ataques contra o alvo têm Vantagem e Invisibilidade não concede benefício normal.",
    "limitation": "",
    "damage": "",
    "attack": true,
    "save": "DES"
  },
  {
    "key": "m1-21",
    "title": "🔎 Leitura da Essência",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "🤝 Toque — objeto, criatura ou efeito",
    "conjuration": "V: pergunta curta. S: toque analítico. M: lente, cristal ou fio condutor. Material: Comum, não consumido; Foco substitui.",
    "effect": "Revela Fonte predominante, propriedades mágicas básicas conhecíveis e vínculos ativos.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-22",
    "title": "🗣️ Língua dos Ecos",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "🧍 Pessoal / 🤝 Toque para escrita",
    "conjuration": "V: recitação curta. S: toque na escrita ou gesto auditivo. M: fragmento de escrita, tinta seca ou casca gravada. Material: Comum, não consumido; Foco substitui.",
    "effect": "Compreende sentido literal de idiomas falados e escrita tocada; não decifra cifras.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-23",
    "title": "🐛 Voz do Enxame",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "🧍 Pessoal — comunicação próxima",
    "conjuration": "V: imitação de sons naturais. S: gesto receptivo. M: alimento, odor ou fragmento do ambiente da criatura. Material: Comum, não consumido; Foco substitui.",
    "effect": "Compreende e comunica ideias simples com criaturas de inteligência animal.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-24",
    "title": "🦋 Companheiro Efêmero",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M",
    "area": "📍 Ponto — manifestação a até 3 m",
    "conjuration": "V: chamado ritual. S: desenho do vínculo. M: pequeno receptáculo, casulo vazio, asa, fio de teia e incenso/resina. Material: Especial; parte do material é consumida no ritual.",
    "effect": "Manifesta/vincula pequena criatura espiritual que explora e segue ordens simples.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-25",
    "title": "🍓 Fruto Revigorante",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M",
    "area": "🤝 Toque — alimentos naturais preparados",
    "conjuration": "V: bênção curta. S: preparo manual. M: frutas, sementes ou alimento natural real. Material: Obrigatório; o alimento é transformado e consumido ao ser ingerido.",
    "effect": "Cria até 5 porções; cada uma cura 1 PV e fornece pequena nutrição.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-26",
    "title": "🧪 Olfato do Perigo",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "🧍 Pessoal — detecção ao redor",
    "conjuration": "V: respiração ritmada. S: gesto sobre sentidos. M: carvão, folha amarga ou pequeno filtro vegetal. Material: Comum, não consumido; Foco substitui.",
    "effect": "Detecta veneno, doença, contaminação ou matéria biologicamente nociva e direção aproximada.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-27",
    "title": "🕸️ Laço Rúnico",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M",
    "area": "🕸️ Ancorada — ponto/superfície tocada",
    "conjuration": "V: palavra de fixação. S: montar/desenhar o laço. M: fibra, fio, raiz, teia ou equivalente. Material: Obrigatório; pode ser perdido/destruído ao ativar.",
    "effect": "Prepara armadilha; DES; falha: Contida. Ação para escapar.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": "DES"
  },
  {
    "key": "m1-28",
    "title": "🧼 Purificação da Seiva",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "⭕ Área curta — comida/água a até 3 m",
    "conjuration": "V: palavra de limpeza. S: gesto sobre o alimento/água. M: carvão limpo, sal mineral, pétala branca ou areia fina. Material: Comum, não consumido; Foco substitui.",
    "effect": "Purifica pequena quantidade de comida/água de contaminações mundanas e toxinas naturais simples.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-29",
    "title": "🫧 Disco de Orvalho",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "📍 Ponto — plataforma surge a até 3 m",
    "conjuration": "V: palavra de sustentação. S: círculo no ar. M: gota de orvalho, disco fino de casca ou fragmento circular. Material: Comum, não consumido; Foco substitui.",
    "effect": "Cria pequena plataforma flutuante para carga/equipamento.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-30",
    "title": "🧭 Chamado do Caminho",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "🧍 Pessoal — direção até destino conhecido",
    "conjuration": "V: nome ou descrição do destino conhecido. S: gesto direcional. M: lembrança física do lugar, mapa, fragmento ou marca associada quando disponível. Material: Comum; Foco substitui se o destino já for realmente conhecido.",
    "effect": "Indica direção geral até destino realmente conhecido.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-31",
    "title": "✨ Enxame de Luz",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "🎯 Múltiplos Alvos — 3 fragmentos, alcance 24 m",
    "conjuration": "V: contagem ou palavra de disparo. S: gesto de multiplicação. M: três sementes brilhantes, contas ou cristais pequenos. Material: Comum, não consumido; Foco substitui.",
    "effect": "Cria 3 fragmentos, cada um causa 1d4+1 Força e acerta automaticamente.",
    "limitation": "",
    "damage": "1d4+1 For",
    "attack": false,
    "save": "FOR"
  },
  {
    "key": "m1-32",
    "title": "🧪 Torrente Corrosiva",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M",
    "area": "➖ Linha de 6 m",
    "conjuration": "V: palavra de corrosão. S: gesto em linha. M: seiva ácida, pó corrosivo ou resina cáustica. Material: Consumível.",
    "effect": "DES; falha: 2d4 Ácido imediato e 2d4 no início dos turnos enquanto coberta. Ação remove.",
    "limitation": "",
    "damage": "2d4",
    "attack": false,
    "save": "DES"
  },
  {
    "key": "m1-33",
    "title": "❄️ Estilhaço de Geada",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "S, M/F",
    "area": "🎯 Alvo + ⭕ Explosão de 1,5 m",
    "conjuration": "S: arremesso. M: lasca de gelo, cristal frio ou fragmento transparente. Material: Comum, não consumido; Foco substitui.",
    "effect": "Ataque Mágico: 1d10 Perfurante; explode e causa 2d6 Frio em 1,5 m, DES para metade.",
    "limitation": "",
    "damage": "1d10 Perfurante",
    "attack": true,
    "save": "DES"
  },
  {
    "key": "m1-34",
    "title": "⚡ Arco Saltitante",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "🔗 Encadeada — alvo inicial + segundo a até 3 m",
    "conjuration": "V: estalo/ordem curta. S: gesto de arco. M: fio metálico, fragmento condutor ou cristal carregado. Material: Comum, não consumido; Foco substitui.",
    "effect": "Ataque Mágico: 2d8 Elétrico; pode saltar para segundo alvo e causar 1d6.",
    "limitation": "",
    "damage": "2d8 El",
    "attack": true,
    "save": ""
  },
  {
    "key": "m1-35",
    "title": "🌍 Peso do Mundo",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M",
    "area": "⭕ Raio de 3 m em ponto a até 18 m",
    "conjuration": "V: palavra grave. S: gesto de compressão. M: pedra densa, metal pesado ou fragmento mineral raro. Material: Especial, não consumido.",
    "effect": "FOR; falha: 2d6 Força e Deslocamento pela metade até fim do próximo turno.",
    "limitation": "",
    "damage": "2d6 For",
    "attack": false,
    "save": "FOR"
  },
  {
    "key": "m1-36",
    "title": "🔥 Revide da Salamandra",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "🎯 Alvo Único — agressor a até 18 m",
    "conjuration": "V: exclamação reativa. S: gesto de retorno. M: escama, carvão ou resina quente. Material: Comum, não consumido; Foco substitui.",
    "effect": "Reação ao sofrer dano; DES; falha: 2d10 Fogo, sucesso: metade.",
    "limitation": "",
    "damage": "2d10 Fogo",
    "attack": false,
    "save": "DES"
  },
  {
    "key": "m1-37",
    "title": "🪲 Carapaça Arcana",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "🤝 Toque — uma criatura",
    "conjuration": "V: palavra de endurecimento. S: traçar placas no corpo. M: fragmento de carapaça, casca ou quitina. Material: Comum, não consumido; Foco substitui.",
    "effect": "Alvo sem armadura apropriada passa a ter CA base 13 + DES.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": "DES"
  },
  {
    "key": "m1-38",
    "title": "🛡️ Asa Interposta",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S",
    "area": "🧍 Pessoal — reação defensiva",
    "conjuration": "V: palavra curta de defesa. S: gesto instantâneo de bloqueio. Material: Nenhum.",
    "effect": "+5 CA até o início do próximo turno, inclusive contra o ataque gatilho.",
    "limitation": "",
    "damage": "",
    "attack": true,
    "save": ""
  },
  {
    "key": "m1-39",
    "title": "🖤 Casca da Noite",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M/F",
    "area": "🧍 Pessoal",
    "conjuration": "V: sussurro sombrio. S: gesto sobre o corpo. M: casca escura, fuligem ou fragmento de quitina negra. Material: Comum, não consumido; Foco substitui.",
    "effect": "Recebe 1d4 + Mod. Conjuração + 4 PV Temporários.",
    "limitation": "",
    "damage": "1d4 + Mod",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-40",
    "title": "🌀 Impulso Cinético",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "S, M",
    "area": "➖ Linha / 🎯 Alvo — trajetória do objeto a até 18 m",
    "conjuration": "S: gesto de lançamento. M: um objeto solto real a ser arremessado. Material: Obrigatório; o objeto é deslocado, não consumido pela magia.",
    "effect": "Arremessa objeto solto real; DES; falha: 3d8 Contundente.",
    "limitation": "",
    "damage": "3d8 Contundente",
    "attack": false,
    "save": "DES"
  },
  {
    "key": "m1-41",
    "title": "🕸️ Ponte de Seda",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M",
    "area": "🕸️ Ancorada — entre dois pontos a até 9 m",
    "conjuration": "V: palavra de ligação. S: traçar os dois pontos. M: seda, teia, fibra ou fio real entre as mãos. Material: Consumível ou incorporado à ponte.",
    "effect": "Cria seda mágica entre dois pontos, servindo como ponte, corda ou linha de escalada.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-42",
    "title": "💧 Prisão de Orvalho",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M",
    "area": "🎯 Alvo Único / 🌊 Água existente — até 12 m",
    "conjuration": "V: palavra de contenção. S: gesto de envolver. M: água real suficiente próxima ao alvo. Material: Obrigatório, não consumido; a água é manipulada.",
    "effect": "Requer água; DES; falha: Contida; repete no fim dos turnos.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": "DES"
  },
  {
    "key": "m1-43",
    "title": "🍄 Nuvem de Esporos",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M",
    "area": "⭕ Raio de 3 m em ponto a até 12 m",
    "conjuration": "V: sopro. S: dispersão. M: esporos reais ou pó fúngico. Material: Consumível.",
    "effect": "CON; falha: 2d6 Veneno e Ofuscada até seu próximo turno. Sucesso: metade.",
    "limitation": "",
    "damage": "2d6 Veneno",
    "attack": false,
    "save": "CON"
  },
  {
    "key": "m1-44",
    "title": "🌺 Explosão de Pólen",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M",
    "area": "⭕ Raio de 3 m em ponto a até 18 m",
    "conjuration": "V: sopro/canto curto. S: dispersão circular. M: pólen real ou pó floral. Material: Consumível.",
    "effect": "SAB; falha: sem Reações e -1d4 no próximo Ataque.",
    "limitation": "",
    "damage": "1d4 no",
    "attack": true,
    "save": "SAB"
  },
  {
    "key": "m1-45",
    "title": "🪲 Manto de Carapaça",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M",
    "area": "🤝 Toque — criatura com proteção natural física",
    "conjuration": "V: palavra de reforço. S: toque. M: carapaça/casca/material rígido natural já usado pelo alvo. Material: Obrigatório, não consumido.",
    "effect": "Fortalece carapaça/casca/material natural rígido já usado pelo alvo: +2 CA.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-46",
    "title": "🔧 Despertar da Sucata",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M",
    "area": "🤝 Toque — mecanismo existente",
    "conjuration": "V: comando curto. S: ativação manual. M: mecanismo real existente e um pequeno condutor/peça de contato. Material: Obrigatório; não consumido, salvo desgaste normal.",
    "effect": "Energiza mecanismo simples existente e parcialmente funcional.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-47",
    "title": "🪤 Pulso da Engrenagem",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M",
    "area": "🤝 Toque / 🌊 Estrutura mecânica conectada",
    "conjuration": "V: palavra de escuta. S: contato. M: a própria máquina/estrutura mecânica. Material: Obrigatório, não consumido.",
    "effect": "Percebe movimento e tensão interna em máquina/estrutura.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-48",
    "title": "🌫️ Eco da Queda",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M",
    "area": "🤝 Toque — superfície marcada pelo evento",
    "conjuration": "V: pergunta curta ou chamado. S: toque prolongado. M: pó, fragmento ou resíduo retirado do próprio local. Material: Especial; uma pequena porção é consumida.",
    "effect": "Revela fragmentos verdadeiros de evento forte recente: sombra, ruído, silhueta, sensação ou palavra.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-49",
    "title": "🩸 Memória da Carapaça",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M",
    "area": "🤝 Toque — fragmento físico de criatura",
    "conjuration": "V: pergunta dirigida ao vestígio. S: exame manual. M: fragmento físico recente da criatura. Material: Especial, não consumido normalmente; pode deteriorar com o tempo.",
    "effect": "Examina fragmento recente de criatura e revela um traço geral.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m1-50",
    "title": "🌱 Refúgio da Folha",
    "level": 1,
    "kind": "completa",
    "source": "",
    "manifestation": "",
    "cast": "",
    "range": "",
    "duration": "",
    "components": "V, S, M",
    "area": "🟫 Zona / 🕸️ Ancorada — abrigo preparado em raio de 3 m",
    "conjuration": "V: recitação/preparo. S: montagem do abrigo. M: folhas, fibras, musgo, casca, terra e material suficiente para o refúgio. Material: Obrigatório; parte fica incorporada ao abrigo.",
    "effect": "Prepara abrigo natural que reduz sinais, abafa ruídos leves e melhora proteção ambiental básica.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-1",
    "title": "🔥 Fenda da Brasa",
    "level": 2,
    "kind": "completa",
    "source": "✨ Arcana",
    "manifestation": "💥 Ruptura",
    "cast": "1 Ação",
    "range": "",
    "duration": "Instantânea",
    "components": "V, S, M/F",
    "area": "➖ Linha de 9 m, 1,5 m de largura",
    "conjuration": "M: carvão, resina seca ou casca queimada; Comum, não consumido; Foco substitui.",
    "effect": "DES; falha: 3d8 Fogo, sucesso: metade. Materiais muito inflamáveis podem incendiar.",
    "limitation": "",
    "damage": "3d8 Fogo",
    "attack": false,
    "save": "DES"
  },
  {
    "key": "m2-2",
    "title": "🌿 Vigor da Colônia",
    "level": 2,
    "kind": "completa",
    "source": "👻 Espiritual / 🌿 Natural",
    "manifestation": "🛡️ Proteção",
    "cast": "1 Ação",
    "range": "",
    "duration": "8 horas",
    "components": "V, S, M/F",
    "area": "🎯 Até 3 criaturas a 9 m",
    "conjuration": "M: três sementes, grãos ou fragmentos de casca; Comum; Foco substitui.",
    "effect": "Cada alvo recebe +5 PV Máximo e +5 PV atuais durante a duração.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-3",
    "title": "💧 Bolha de Orvalho",
    "level": 2,
    "kind": "completa",
    "source": "✨ Arcana / 🌿 Natural",
    "manifestation": "🛡️ Proteção",
    "cast": "1 Ação",
    "range": "",
    "duration": "24 horas",
    "components": "S",
    "area": "🎯 Alvo Único a 18 m",
    "conjuration": "Nenhum.",
    "effect": "Cria membrana de ar respirável. Permite respirar em água, lama líquida, fumaça comum e ambientes com ar insuficiente.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-4",
    "title": "🦋 Forma Adaptável",
    "level": 2,
    "kind": "completa",
    "source": "🌿 Natural / ✨ Arcana",
    "manifestation": "🌀 Alteração",
    "cast": "1 Ação",
    "range": "",
    "duration": "Concentração, até 1 hora",
    "components": "V, S",
    "area": "🧍 Pessoal",
    "conjuration": "Nenhum.",
    "effect": "Escolha uma adaptação: Aquática, Saltadora, Carapaça (+1 CA) ou Aderente (escalada).",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-5",
    "title": "🐝 Mensageiro do Jardim",
    "level": 2,
    "kind": "completa",
    "source": "🌿 Natural",
    "manifestation": "🎭 Influência",
    "cast": "1 Ação ou Ritual",
    "range": "",
    "duration": "24 horas",
    "components": "V, S, M",
    "area": "🎯 Criatura minúscula não hostil a 9 m",
    "conjuration": "M: alimento apropriado; Consumível.",
    "effect": "A criatura leva uma mensagem curta e tenta alcançar um destino definido.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-6",
    "title": "⚙️ Sussurro da Engrenagem",
    "level": 2,
    "kind": "completa",
    "source": "✨ Arcana",
    "manifestation": "🌀 Alteração",
    "cast": "1 Ação",
    "range": "",
    "duration": "Concentração, até 10 min",
    "components": "S, M",
    "area": "🤝 Toque — mecanismo",
    "conjuration": "M: fio metálico ou condutor; Especial, não consumido.",
    "effect": "Interage com mecanismo funcional: ativar, interromper, destravar, inverter ou redirecionar função simples; complexos podem exigir teste.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-7",
    "title": "🔐 Lacre da Seda",
    "level": 2,
    "kind": "completa",
    "source": "✨ Arcana",
    "manifestation": "🛡️ Proteção",
    "cast": "1 Ação",
    "range": "",
    "duration": "Até ser dissipada",
    "components": "V, S, M",
    "area": "🕸️ Ancorada — objeto/passagem tocada",
    "conjuration": "M: seda tratada com resina/selo; Especial, consumido.",
    "effect": "Fecha magicamente porta, recipiente ou passagem; define condição simples de acesso.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-8",
    "title": "🍂 Presságio das Folhas",
    "level": 2,
    "kind": "completa",
    "source": "👻 Espiritual",
    "manifestation": "👁️ Percepção",
    "cast": "1 minuto ou Ritual",
    "range": "",
    "duration": "Instantânea",
    "components": "V, S, M",
    "area": "🧍 Pessoal",
    "conjuration": "M: folhas, sementes, pequenas pedras ou restos naturais marcados; Especial, não consumido.",
    "effect": "Pergunta sobre ação nos próximos 30 min; Mestre responde Favorável, Desfavorável, Incerto ou Silêncio.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-9",
    "title": "🌳 Couraça de Casca",
    "level": 2,
    "kind": "completa",
    "source": "🌿 Natural",
    "manifestation": "🛡️ Proteção",
    "cast": "1 Ação",
    "range": "",
    "duration": "Concentração, até 1 hora",
    "components": "V, S, M/F",
    "area": "🤝 Toque",
    "conjuration": "M: fragmento de casca resistente; Comum; Foco substitui.",
    "effect": "Alvo recebe +2 CA; não acumula com outro bônus mágico direto de CA.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-10",
    "title": "👁️ Olhos Emprestados",
    "level": 2,
    "kind": "completa",
    "source": "🌿 Natural / 👻 Espiritual",
    "manifestation": "👁️ Percepção",
    "cast": "1 Ação ou Ritual",
    "range": "",
    "duration": "Concentração, até 1 hora",
    "components": "S",
    "area": "🤝 Toque — criatura animal voluntária",
    "conjuration": "Nenhum.",
    "effect": "Usa sentidos da criatura; enquanto faz isso fica cego/surdo ao próprio corpo.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-11",
    "title": "🌑 Véu dos Sentidos",
    "level": 2,
    "kind": "completa",
    "source": "👻 Espiritual / 🎭 Expressiva",
    "manifestation": "🎭 Influência",
    "cast": "1 Ação",
    "range": "",
    "duration": "1 min",
    "components": "V",
    "area": "🎯 Alvo Único a 18 m",
    "conjuration": "Nenhum.",
    "effect": "CON; falha: escolha Cego ou Surdo. Repete Salvaguarda no fim de cada turno.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": "CON"
  },
  {
    "key": "m2-12",
    "title": "🪞 Corpo Tremeluzente",
    "level": 2,
    "kind": "completa",
    "source": "✨ Arcana / 🎭 Expressiva",
    "manifestation": "🛡️ Proteção",
    "cast": "1 Ação",
    "range": "",
    "duration": "Concentração, até 1 min",
    "components": "V",
    "area": "🧍 Pessoal",
    "conjuration": "Nenhum.",
    "effect": "Sua imagem fica borrada; ataques contra você sofrem -1d4.",
    "limitation": "",
    "damage": "1d4",
    "attack": true,
    "save": ""
  },
  {
    "key": "m2-13",
    "title": "📚 Saber Emprestado",
    "level": 2,
    "kind": "completa",
    "source": "👻 Espiritual",
    "manifestation": "👁️ Percepção",
    "cast": "1 Ação",
    "range": "",
    "duration": "1 hora",
    "components": "V, S, M/F",
    "area": "🧍 Pessoal",
    "conjuration": "M: página, ferramenta simbólica ou objeto ligado à perícia; Comum; Foco substitui.",
    "effect": "Escolha uma perícia na qual não é proficiente; ganha Proficiência nela durante a duração.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-14",
    "title": "🌟 Marca Reveladora",
    "level": 2,
    "kind": "completa",
    "source": "✨ Arcana / 👻 Espiritual",
    "manifestation": "👁️ Percepção",
    "cast": "Ação Bônus",
    "range": "",
    "duration": "Concentração, até 1 min",
    "components": "V",
    "area": "🧍 Pessoal / próxima arma",
    "conjuration": "Nenhum.",
    "effect": "Seu próximo acerto com arma causa +2d6 Radiante/Espiritual e revela o alvo, anulando benefício normal de Invisibilidade até o fim do próximo turno.",
    "limitation": "",
    "damage": "2d6 Radiante",
    "attack": true,
    "save": ""
  },
  {
    "key": "m2-15",
    "title": "🕊️ Maré de Serenidade",
    "level": 2,
    "kind": "completa",
    "source": "🎭 Expressiva / 👻 Espiritual",
    "manifestation": "🎭 Influência",
    "cast": "1 Ação",
    "range": "",
    "duration": "Concentração, até 1 min",
    "components": "V, S",
    "area": "⭕ Raio de 6 m em ponto a até 18 m",
    "conjuration": "Nenhum.",
    "effect": "CAR; falha: suprime Amedrontado/Enfeitiçado ou reduz hostilidade intensa enquanto permanecer na área.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": "CAR"
  },
  {
    "key": "m2-16",
    "title": "🗡️ Coroa de Estilhaços",
    "level": 2,
    "kind": "completa",
    "source": "✨ Arcana",
    "manifestation": "🕸️ Manifestação",
    "cast": "1 Ação",
    "range": "",
    "duration": "Concentração, até 1 min",
    "components": "V, S, M/F",
    "area": "🟫 Zona de 3 m em ponto a 18 m",
    "conjuration": "M: pequenos cacos, espinhos ou lâminas simbólicas; Comum; Foco substitui.",
    "effect": "Área perigosa; criatura que entra ou começa turno sofre 4d4 Cortante.",
    "limitation": "",
    "damage": "4d4 Cortante",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-17",
    "title": "🔥 Chama Perene",
    "level": 2,
    "kind": "completa",
    "source": "✨ Arcana",
    "manifestation": "🕸️ Manifestação",
    "cast": "1 Ação",
    "range": "",
    "duration": "Até ser dissipada",
    "components": "V, S, M",
    "area": "🤝 Toque — objeto",
    "conjuration": "M: resina rara ou pó luminoso; Especial, consumido.",
    "effect": "Cria chama que ilumina mas não consome combustível nem causa calor destrutivo normal.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-18",
    "title": "🪶 Círculo de Espinhos",
    "level": 2,
    "kind": "completa",
    "source": "🌿 Natural / ✨ Arcana",
    "manifestation": "🛡️ Proteção",
    "cast": "1 Ação",
    "range": "",
    "duration": "8 horas",
    "components": "V, S, M",
    "area": "⭕ Raio de 3 m em torno do conjurador",
    "conjuration": "M: 4 espinhos, dardos, sementes duras ou equivalentes; Consumíveis.",
    "effect": "Primeiras criaturas hostis que entram podem ser atingidas automaticamente por projéteis mágicos, até o número preparado.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-19",
    "title": "👑 Coroa da Discórdia",
    "level": 2,
    "kind": "completa",
    "source": "🎭 Expressiva / 👻 Espiritual",
    "manifestation": "🎭 Influência",
    "cast": "1 Ação",
    "range": "",
    "duration": "Concentração, até 1 min",
    "components": "V, S",
    "area": "🎯 Alvo Único a 18 m",
    "conjuration": "Nenhum.",
    "effect": "SAB; falha: alvo fica mentalmente desorganizado e pode atacar criatura próxima; repete Salvaguarda.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": "SAB"
  },
  {
    "key": "m2-20",
    "title": "🌘 Manto de Escuridão",
    "level": 2,
    "kind": "completa",
    "source": "👻 Espiritual / ✨ Arcana",
    "manifestation": "🕸️ Manifestação",
    "cast": "1 Ação",
    "range": "",
    "duration": "Concentração, até 10 min",
    "components": "V, M/F",
    "area": "⭕ Raio de 4,5 m em ponto a 18 m",
    "conjuration": "M: carvão negro, fuligem ou pétala escura; Comum; Foco substitui.",
    "effect": "Cria escuridão mágica que bloqueia visão comum e visão no escuro normal.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-21",
    "title": "👁️ Visão do Breu",
    "level": 2,
    "kind": "completa",
    "source": "🌿 Natural / ✨ Arcana",
    "manifestation": "🌀 Alteração",
    "cast": "1 Ação",
    "range": "",
    "duration": "8 horas",
    "components": "V, S, M/F",
    "area": "🤝 Toque",
    "conjuration": "M: olho seco, carvão ou escama escura; Comum; Foco substitui.",
    "effect": "Alvo recebe visão no escuro.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-22",
    "title": "🧠 Escuta Superficial",
    "level": 2,
    "kind": "completa",
    "source": "👻 Espiritual",
    "manifestation": "👁️ Percepção",
    "cast": "1 Ação",
    "range": "",
    "duration": "Concentração, até 1 min",
    "components": "V, S, M/F",
    "area": "🧍 Pessoal — percepção mental em 9 m",
    "conjuration": "M: fio fino, cristal ou objeto pessoal; Comum; Foco substitui.",
    "effect": "Percebe pensamentos superficiais; aprofundar exige SAB e pode revelar a intrusão.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": "SAB"
  },
  {
    "key": "m2-23",
    "title": "🐉 Sopro Emprestado",
    "level": 2,
    "kind": "completa",
    "source": "🌿 Natural / ✨ Arcana",
    "manifestation": "🌀 Alteração",
    "cast": "Ação Bônus",
    "range": "",
    "duration": "Concentração, até 1 min",
    "components": "V, S, M/F",
    "area": "🤝 Toque",
    "conjuration": "M: escama, brasa, cristal frio, gota ácida ou condutor conforme elemento; Comum; Foco substitui.",
    "effect": "Alvo ganha ação para exalar cone curto de Ácido, Frio, Fogo, Elétrico ou Veneno; 3d6, DES para metade.",
    "limitation": "",
    "damage": "3d6",
    "attack": false,
    "save": "DES"
  },
  {
    "key": "m2-24",
    "title": "🌪️ Redemoinho de Poeira",
    "level": 2,
    "kind": "completa",
    "source": "🌿 Natural / ✨ Arcana",
    "manifestation": "🕸️ Manifestação",
    "cast": "1 Ação",
    "range": "",
    "duration": "Concentração, até 1 min",
    "components": "V, S, M/F",
    "area": "📍 Ponto a 18 m",
    "conjuration": "M: pó, areia ou terra fina; Comum; Foco substitui.",
    "effect": "Cria redemoinho móvel; FOR ao entrar/começar turno: 1d8 Contundente e empurra 1,5 m.",
    "limitation": "",
    "damage": "1d8 Contundente",
    "attack": false,
    "save": "FOR"
  },
  {
    "key": "m2-25",
    "title": "🪨 Peso das Asas",
    "level": 2,
    "kind": "completa",
    "source": "✨ Arcana",
    "manifestation": "🌀 Alteração",
    "cast": "1 Ação",
    "range": "",
    "duration": "Concentração, até 1 min",
    "components": "V",
    "area": "🎯 Alvo Único a 36 m",
    "conjuration": "Nenhum.",
    "effect": "FOR; falha: criatura voadora perde altitude e não pode ganhar altura; deslocamento aéreo é reduzido.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": "FOR"
  },
  {
    "key": "m2-26",
    "title": "💪 Dádiva do Corpo",
    "level": 2,
    "kind": "completa",
    "source": "🌿 Natural / 👻 Espiritual",
    "manifestation": "🌀 Alteração",
    "cast": "1 Ação",
    "range": "",
    "duration": "Concentração, até 1 hora",
    "components": "V, S, M/F",
    "area": "🤝 Toque",
    "conjuration": "M: símbolo animal/vegetal ligado ao atributo; Comum; Foco substitui.",
    "effect": "Escolha FOR, DES, CON, INT, SAB ou CAR; alvo recebe Vantagem em testes desse atributo.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": "FOR"
  },
  {
    "key": "m2-27",
    "title": "🔍 Engrandecer / Encolher",
    "level": 2,
    "kind": "completa",
    "source": "✨ Arcana",
    "manifestation": "🌀 Alteração",
    "cast": "1 Ação",
    "range": "",
    "duration": "Concentração, até 1 min",
    "components": "V, S, M/F",
    "area": "🎯 Alvo Único a 9 m",
    "conjuration": "M: semente e casca pequena; Comum; Foco substitui.",
    "effect": "Aumenta ou reduz um passo de tamanho dentro dos limites do Minimundo; ajusta alcance, força e presença física de forma moderada.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": "FOR"
  },
  {
    "key": "m2-28",
    "title": "🎭 Fascínio da Plateia",
    "level": 2,
    "kind": "completa",
    "source": "🎭 Expressiva",
    "manifestation": "🎭 Influência",
    "cast": "1 Ação",
    "range": "",
    "duration": "1 min",
    "components": "V, S",
    "area": "⭕ Raio de 12 m em torno do conjurador",
    "conjuration": "Nenhum.",
    "effect": "Criaturas que falham em SAB têm dificuldade de prestar atenção em outros alvos e sofrem Desvantagem em Percepção contra terceiros.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": "SAB"
  },
  {
    "key": "m2-29",
    "title": "🪲 Montaria Vinculada",
    "level": 2,
    "kind": "completa",
    "source": "🌿 Natural / 👻 Espiritual",
    "manifestation": "🕸️ Manifestação",
    "cast": "10 min",
    "range": "",
    "duration": "Persistente até dispensada",
    "components": "V, S, M",
    "area": "📍 Ponto a 9 m",
    "conjuration": "M: sela, fita, marca de vínculo ou símbolo de montaria; Especial, não consumido.",
    "effect": "Manifesta ou vincula pequena montaria espiritual apropriada ao Minimundo.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-30",
    "title": "🧭 Sentido das Armadilhas",
    "level": 2,
    "kind": "completa",
    "source": "👻 Espiritual / ✨ Arcana",
    "manifestation": "👁️ Percepção",
    "cast": "1 Ação",
    "range": "",
    "duration": "Instantânea",
    "components": "V, S",
    "area": "🧍 Pessoal — até 36 m",
    "conjuration": "Nenhum.",
    "effect": "Percebe presença de perigos deliberadamente preparados, sem revelar posição exata, tipo ou mecanismo.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-31",
    "title": "🔥 Lâmina de Brasa",
    "level": 2,
    "kind": "completa",
    "source": "✨ Arcana / 🌿 Natural",
    "manifestation": "🕸️ Manifestação",
    "cast": "Ação Bônus",
    "range": "",
    "duration": "Concentração, até 10 min",
    "components": "V, S, M/F",
    "area": "🧍 Pessoal",
    "conjuration": "M: espinho, graveto ou foco alongado; Comum; Foco substitui.",
    "effect": "Cria lâmina de fogo; ataques corpo a corpo mágicos causam 3d6 Fogo.",
    "limitation": "",
    "damage": "3d6 Fogo",
    "attack": true,
    "save": ""
  },
  {
    "key": "m2-32",
    "title": "🔥 Orbe Incandescente",
    "level": 2,
    "kind": "completa",
    "source": "✨ Arcana",
    "manifestation": "🕸️ Manifestação",
    "cast": "1 Ação",
    "range": "",
    "duration": "Concentração, até 1 min",
    "components": "V, S, M/F",
    "area": "📍 Ponto a 18 m",
    "conjuration": "M: bola de resina, carvão ou semente redonda; Comum; Foco substitui.",
    "effect": "Cria esfera flamejante móvel; ao colidir, DES: 2d6 Fogo. Pode mover com Ação Bônus.",
    "limitation": "",
    "damage": "2d6 Fogo",
    "attack": false,
    "save": "DES"
  },
  {
    "key": "m2-33",
    "title": "🦋 Revoada Familiar",
    "level": 2,
    "kind": "completa",
    "source": "🌿 Natural / 👻 Espiritual",
    "manifestation": "🕸️ Manifestação",
    "cast": "1 min",
    "range": "",
    "duration": "Concentração, até 1 hora",
    "components": "V, S",
    "area": "🤝 Toque / área próxima",
    "conjuration": "Nenhum.",
    "effect": "Manifesta até 3 pequenos familiares efêmeros para reconhecimento e tarefas simples.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-34",
    "title": "🍀 Favor do Acaso",
    "level": 2,
    "kind": "completa",
    "source": "👻 Espiritual",
    "manifestation": "🛡️ Proteção",
    "cast": "1 min",
    "range": "",
    "duration": "1 hora",
    "components": "V, S, M",
    "area": "🎯 Alvo Único a 18 m",
    "conjuration": "M: pequena peça rara, cristal ou símbolo de sorte; Especial, consumido.",
    "effect": "Uma vez durante a duração, alvo pode rerrolar um ataque, teste ou Salvaguarda e deve usar o novo resultado.",
    "limitation": "",
    "damage": "",
    "attack": true,
    "save": ""
  },
  {
    "key": "m2-35",
    "title": "⚰️ Sono Sereno",
    "level": 2,
    "kind": "completa",
    "source": "👻 Espiritual",
    "manifestation": "🛡️ Proteção",
    "cast": "1 Ação ou Ritual",
    "range": "",
    "duration": "10 dias",
    "components": "V, S, M",
    "area": "🤝 Toque — cadáver",
    "conjuration": "M: sal, pétalas secas ou resina funerária; Consumível.",
    "effect": "Retarda decomposição e protege o corpo de efeitos menores que o corromperiam.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-36",
    "title": "🗣️ Palavra Reescrita",
    "level": 2,
    "kind": "completa",
    "source": "🎭 Expressiva / 👻 Espiritual",
    "manifestation": "🎭 Influência",
    "cast": "Reação",
    "range": "",
    "duration": "Instantânea",
    "components": "V, S, M/F",
    "area": "🧍 Pessoal / conversa próxima",
    "conjuration": "M: pequeno sino, ficha ou conta; Comum; Foco substitui.",
    "effect": "Após dizer algo, altera magicamente a lembrança imediata da frase para uma versão curta diferente, dentro de limites razoáveis.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-37",
    "title": "🌬️ Corredor de Vento",
    "level": 2,
    "kind": "completa",
    "source": "🌿 Natural / ✨ Arcana",
    "manifestation": "🌀 Alteração",
    "cast": "1 Ação",
    "range": "",
    "duration": "Concentração, até 1 min",
    "components": "V, S, M/F",
    "area": "➖ Linha de 18 m",
    "conjuration": "M: folha leve ou pena; Comum; Foco substitui.",
    "effect": "Linha de vento forte empurra criaturas, dispersa gases e torna movimento contra ela difícil.",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  },
  {
    "key": "m2-38",
    "title": "🌟 Espírito Restaurador",
    "level": 2,
    "kind": "completa",
    "source": "👻 Espiritual / 🌿 Natural",
    "manifestation": "🕸️ Manifestação",
    "cast": "Ação Bônus",
    "range": "",
    "duration": "Concentração, até 1 min",
    "components": "V, S",
    "area": "📍 Ponto a 18 m",
    "conjuration": "Nenhum.",
    "effect": "Invoca espírito curativo; primeira criatura ali por rodada recupera 1d6 + Mod. Conjuração, com limite de usos.",
    "limitation": "",
    "damage": "1d6 + Mod",
    "attack": false,
    "save": ""
  },
  {
    "key": "completa-119",
    "title": "🔥 Metal Rubro",
    "level": 2,
    "kind": "completa",
    "source": "✨ Arcana",
    "manifestation": "🌀 Alteração",
    "cast": "1 Ação",
    "range": "",
    "duration": "Concentração, até 1 min 🎼 3ª Melodia — 67 referências Inventário para auditoria 5e 2014/5.5 → Microcosmos. Nada desta seção entra no Codex definitivo sem revisão. # Referência 5e Nome Microcosmos provisório Escola Status 01 Animate Dead Servo da Carapaça Necromancia REVISAR",
    "components": "",
    "area": "",
    "conjuration": "",
    "effect": "",
    "limitation": "",
    "damage": "",
    "attack": false,
    "save": ""
  }
];

